run:
  build-tags:
    - e2e
  skip-dirs:
    - vendor
linters-settings:
  errcheck:
    exclude: .errcheck.txt
linters:
  enable:
  - errcheck
  - gofumpt
  - goimports
  - gosec
  - gocritic
  - golint
  - misspell
  - deadcode
  - gomnd
