run:
  build-tags:
    - e2e
  skip-dirs:
    - vendor
linters-settings:
  errcheck:
    exclude: .errcheck.txt
linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - exhaustive
    # - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - dupl
    - errcheck
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - gocritic
    - misspell
    - deadcode
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - makezero
    - nakedret
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - unused
    - unparam
    - gochecknoinits
    - goconst
      # - gocyclo
    # - goerr113
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    #- unconvert
    - wastedassign
    - whitespace
