---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipelines-as-code
  namespace: pipelines-as-code
  labels:
    pipelines-as-code/route: controller
spec:
  ingressClassName: nginx
  rules:
  - host: "controller.%DOMAIN_NAME%"
    http:
      paths:
      - backend:
          service:
            name: "%SERVICE_NAME%"
            port:
              number: 8080
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.%DOMAIN_NAME%
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097
