# This is a sample application, which doesn't have a secret, if you use a
# Github app installation (preferred) you don't have to specify a secret.
---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sample-app
  namespace: "sample-ci"
spec:
  # which URL this Repository handles
  url: "https://github.com/owner/sample-app"
