# Copyright 2021 Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipelines-as-code-interceptor
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code
spec:
  serviceAccountName: pipelines-as-code-sa-el
  triggers:

    # When you have a /retest in a comment to retest a PR
    - name: github-issue-comment-retest
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-app-secret"
                secretKey: "webhook.secret"
            - name: "eventTypes"
              value: ["issue_comment"]
        - name: "Handle /retest comment in issue"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                  body.action == 'created' &&
                  'pull_request' in body.issue &&
                  body.issue.state == 'open' &&
                  'installation' in body &&
                  body.comment.body.matches('(^|\\r\\n)/retest([ ]*$|$|\\r\\n)')
      bindings:
        - ref: pipelines-as-code-bindings-retest-comment
      template:
        ref: pipelines-as-code-template-retest-comment

    # When you have a /ok-to-test in a comment to allow CI on a non owner sender
    - name: github-issue-comment-ok-to-test
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-app-secret"
                secretKey: "webhook.secret"
            - name: "eventTypes"
              value: ["issue_comment"]
        - name: "Handle /ok-to-test comment in issue"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                  body.action == 'created' &&
                  'pull_request' in body.issue &&
                  body.issue.state == 'open' &&
                  'installation' in body &&
                  body.comment.body.matches('(^|\\r\\n)/ok-to-test([ ]*$|$|\\r\\n)')
      bindings:
        - ref: pipelines-as-code-bindings-ok-to-test-comment
      template:
        # Using the templateRef from retest since they are mostly the same
        ref: pipelines-as-code-template-retest-comment

    # Branch push using different binding but same triggertemplate as pullreq
    - name: github-branch-push
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-app-secret"
                secretKey: "webhook.secret"
            - name: "eventTypes"
              value: ["push"]
        - name: "Branch Push"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                'installation' in body &&
                'pusher' in body &&
                'installation' in body
      bindings:
        - ref: pipelines-as-code-bindings-push
      template:
        ref: pipelines-as-code-template-push

    # When using the UI and clicking on Re-run failed test
    - name: github-check-run-recheck
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-app-secret"
                secretKey: "webhook.secret"
            - name: "eventTypes"
              value: ["check_run"]
        - name: "UI rerun failed CI click"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                body.action in ['rerequested'] &&
                'check_run' in body
      bindings:
        - ref: pipelines-as-code-bindings-recheck
      template:
        ref: pipelines-as-code-template-recheck

    # When sending a new Pull Request
    - name: github-pull-request
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-app-secret"
                secretKey: "webhook.secret"
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "Pull request - created/updated"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                body.action in ['created', 'synchronize', 'opened']
      bindings:
        - ref: pipelines-as-code-bindings-pullreq
      template:
        ref: pipelines-as-code-template-pullreq
