---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: openshift-pipelines-ascode-interceptor
  namespace: pipelines-ascode
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: openshift-pipelines-ascode
spec:
  serviceAccountName: openshift-pipelines-ascode-sa-el
  triggers:
    # When you have a /retest in a comment to retest a PR
    - name: github-issue-comment-retest
      bindings:
        - ref: openshift-pipelines-ascode-bindings-retest-comment
      interceptors:
        - github:
            secretRef:
              secretName: "github-app-secret"
              secretKey: "webhook.secret"
            eventTypes:
              - issue_comment
        - cel:
            filter: >-
              body.action == 'created' &&
              'pull_request' in body.issue &&
              body.issue.state == 'open' &&
              'installation' in body &&
              body.comment.body.matches('(^|\\r\\n)/retest([ ]*$|$|\\r\\n)')
      template:
        ref: openshift-pipelines-ascode-template-retest-comment

    # When you have a /ok-to-test in a comment to allow CI on a non owner sender
    - name: github-issue-comment-retest
      bindings:
        - ref: openshift-pipelines-ascode-bindings-ok-to-test-comment
      interceptors:
        - github:
            secretRef:
              secretName: "github-app-secret"
              secretKey: "webhook.secret"
            eventTypes:
              - issue_comment
        - cel:
            filter: >-
              body.action == 'created' &&
              'pull_request' in body.issue &&
              body.issue.state == 'open' &&
              'installation' in body &&
              body.comment.body.matches('(^|\\r\\n)/ok-to-test([ ]*$|$|\\r\\n)')
      template:
        # Using retest comment since it was the first one
        ref: openshift-pipelines-ascode-template-retest-comment

    # Branch push using different binding but same triggertemplate as pullreq
    - name: github-branch-push
      bindings:
        - ref: openshift-pipelines-ascode-bindings-push
      interceptors:
        - github:
            secretRef:
              secretName: "github-app-secret"
              secretKey: "webhook.secret"
            eventTypes:
              - push
        - cel:
            filter: >-
              'installation' in body &&
              'pusher' in body
      template:
        ref: openshift-pipelines-ascode-template-push

    # When using the UI and clicking on Re-run failed test
    - name: github-check-run-recheck
      bindings:
        - ref: openshift-pipelines-ascode-bindings-recheck
      interceptors:
        - github:
            secretRef:
              secretName: "github-app-secret"
              secretKey: "webhook.secret"
            eventTypes:
              - check_run
        - cel:
            filter: >-
              body.action in ['rerequested'] && 'check_run' in body && 'installation' in body
      template:
        ref: openshift-pipelines-ascode-template-recheck

    # When sending a new Pull Request
    - name: github-pull-request
      bindings:
        - ref: openshift-pipelines-ascode-bindings-pullreq
      interceptors:
        - github:
            secretRef:
              secretName: "github-app-secret"
              secretKey: "webhook.secret"
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.action in ['created', 'synchronize', 'opened'] && 'installation' in body
      template:
        ref: openshift-pipelines-ascode-template-pullreq
# Triggers >0.13 Changed almost everything for EventListener
# ---
# apiVersion: triggers.tekton.dev/v1alpha1
# kind: EventListener
# metadata:
#   name: openshift-pipelines-ascode-interceptor
#   namespace: pipelines-ascode
#   labels:
#     app.kubernetes.io/instance: default
#     app.kubernetes.io/part-of: openshift-pipelines-ascode
# spec:
#   triggers:
#     - name: github-listener
#       interceptors:
#         # TODO: Add webhook secret
#         - ref:
#             name: github-listener
#           params:
#             - name: "eventTypes"
#               value: ["pull_request", "issue_comment"]
#         - name: "Only form a Github APP and PR Opened, Created, Syncronized"
#           ref:
#             name: "cel"
#           params:
#             - name: "filter"
#               value: "body.action in ['created', 'opened', 'synchronize'] && 'installation' in body"
#       bindings:
#         - ref: openshift-pipelines-ascode-bindings
#       template:
#         ref: openshift-pipelines-ascode-template
#   resources:
#     kubernetesResource:
#       spec:
#         template:
#           spec:
#             serviceAccountName: openshift-pipelines-ascode-sa-el
