---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipelines-as-code-test
spec:
  workspaces:
    - name: source
  params:
    - name: repo_url
    - name: revision
  tasks:
    - name: fetchit
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: check
      runAfter: [fetchit]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: check
            workingDir: $(workspaces.source.path)
            image: gcr.io/tekton-releases/dogfooding/test-runner
            script: |
              make test lint GO_TEST_FLAGS="-coverprofile=coverage.txt -covermode=atomic"
      workspaces:
        - name: source
          workspace: source
    - name: codecov
      runAfter: [check]
      taskRef:
        name: codecov
      params:
        - name: codecov-token-secret
          value: "pipelines-as-code-codecov-token"
        - name: codecov-token-secret-key
          value: "token"
      workspaces:
        - name: source
          workspace: source
